### ISSUE TITLE
Your reference doesn't appear to be indexed

### ISSUE THREAD

**Issue by wjyzidane** [klarman-cell-observatory/KCO#8]
Hello,

I am using cellranger_workflow at the Terra for 10x scATAC-seq data processing. I chose hg19 or hg19 v3.0.0 in sample_sheet.csv but get the error:

[error] Your reference doesn't appear to be indexed. Please run the mkreference tool.

I wonder is it because the hg19 reference is not loaded or not indexed?

Thanks,

**Comment by joshua-gould** [comment]
hg19 is for cellranger, not cellranger-atac. We currently have GRCh38_atac_v1.0.1 and mm10_atac_v1.0.1

**Comment by wjyzidane** [comment]
Thanks! 

Is that possible to add a hg19 version or can I add it myself? As all my other data are the hg19 version, it would be easier if we want to compare.

**Comment by joshua-gould** [comment]
Would you like the reference added for version 1.0.1 or 1.1.0?

**Comment by wjyzidane** [comment]
I would appreciate the version 1.0.1. Thanks a lot!

**Comment by wjyzidane** [comment]
Hello, No rush and just check in to see if there is a hg19 reference for ATAC-seq available. Thanks.

**Comment by joshua-gould** [comment]
You can use the keyword hg19_atac_v1.0.1 for hg19 ATAC.
